
// API
export const API = 'API';

// TASKS
export const FETCH_TASKS_REQUEST = 'TASK::FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'TASK::FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_ERROR = 'TASK::FETCH_TASKS_ERROR';
export const UPDATE_TASKS_REQUEST = 'TASK::UPDATE_TASKS_REQUEST';
export const UPDATE_TASKS_SUCCESS = 'TASK::UPDATE_TASKS_SUCCESS';
export const UPDATE_TASKS_ERROR = 'TASK::UPDATE_TASKS_ERROR';
export const CREATE_TASK_REQUEST = 'TASK::CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'TASK::CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'TASK::CREATE_TASK_ERROR';
export const EDIT_TASK_REQUEST = 'TASK::EDIT_TASK_REQUEST';
export const EDIT_TASK_SUCCESS = 'TASK::EDIT_TASK_SUCCESS';
export const EDIT_TASK_ERROR = 'TASK::EDIT_TASK_ERROR';
export const DELETE_TASK_REQUEST = 'TASK::DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'TASK::DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'TASK::DELETE_TASK_ERROR';

// SESSION
export const LOGIN_REQUEST = 'SESSION::LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'SESSION::LOGIN_SUCCESS';
export const LOGIN_ERROR = 'SESSION::LOGIN_ERROR';
export const LOGOUT_REQUEST = 'SESSION::LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'SESSION::LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'SESSION::LOGOUT_ERROR';
export const SIGN_UP_REQUEST = 'SESSION::SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SESSION::SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SESSION::SIGN_UP_ERROR';

// BOARD
export const UPDATE_LAYOUTS = 'BOARD::UPDATE_LAYOUTS';
export const BUILD_LAYOUTS = 'BOARD::BUILD_LAYOUTS';
export const ADD_LAYOUT = 'BOARD::ADD_LAYOUT';
export const REMOVE_LAYOUT = 'BOARD::REMOVE_LAYOUT';

// MODAL
export const ACTIVATE_TASK_MODAL = 'MODAL::ACTIVATE_TASK_MODAL';
export const DISABLE_TASK_MODAL = 'MODAL::DISABLE_TASK_MODAL';
