
//API
export const API = 'API';

// ERRORS
export const RECEIVE_ERROR = 'ERROR::RECEIVE_ERROR';

// TASKS
export const RECEIVE_TASKS = 'TASKS::RECEIVE_TASKS';
export const RECEIVE_TASK = 'TASKS::RECEIVE_TASK';
export const REMOVE_TASK = 'TASKS::REMOVE_TASK';

// SESSION
export const LOGIN_REQUEST = 'SESSION::LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'SESSION::LOGIN_SUCCESS';
export const LOGIN_ERROR = 'SESSION::LOGIN_ERROR';
export const LOGOUT_REQUEST = 'SESSION::LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'SESSION::LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'SESSION::LOGOUT_ERROR';
export const SIGN_UP_REQUEST = 'SESSION::SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SESSION::SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SESSION::SIGN_UP_ERROR';

// USER
export const RECEIVE_USER = 'USER::RECEIVE_USER';

// BOARD
export const UPDATE_LAYOUTS = 'BOARD::UPDATE_LAYOUTS';
export const BUILD_LAYOUTS = 'BOARD::BUILD_LAYOUTS';
export const ADD_LAYOUT = 'BOARD::ADD_LAYOUT';
export const REMOVE_LAYOUT = 'BOARD::REMOVE_LAYOUT';

// MODAL
export const ACTIVATE_TASK_MODAL = 'MODAL::ACTIVATE_TASK_MODAL';
export const DISABLE_TASK_MODAL = 'MODAL::DISABLE_TASK_MODAL';
