
//API
export const API = 'API';

// ERRORS
export const RECEIVE_ERROR = 'ERROR::RECEIVE_ERROR';

// TASKS
export const RECEIVE_TASKS = 'TASKS::RECEIVE_TASKS';
export const RECEIVE_TASK = 'TASKS::RECEIVE_TASK';
export const DELETE_TASK_SUCCESS = 'TASKS::DELETE_TASK';

// SESSION
export const RECEIVE_CURRENT_USER = 'SESSION::RECEIVE_CURRENT_USER'

// USER
export const RECEIVE_USER = 'USER::RECEIVE_USER';

// BOARD
export const UPDATE_LAYOUTS = 'BOARD::UPDATE_LAYOUTS';
export const BUILD_LAYOUTS = 'BOARD::BUILD_LAYOUTS';
export const ADD_LAYOUT = 'BOARD::ADD_LAYOUT';
